import collections
import typing
from typing import Any

class SampleSet:
    items: Any = ...
    positions: Any = ...
    def __init__(self, items: typing.Optional[typing.Iterable[collections.abc.Hashable]]=...) -> None: ...
    def replace(self, old: collections.abc.Hashable, new: collections.abc.Hashable, check: bool=...) -> None: ...
    def add(self, item: Any) -> None: ...
    def remove(self, item: Any) -> None: ...
    def choice(self): ...
    def __contains__(self, item: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def __getitem__(self, item: Any): ...
