import collections
import typing

def assert_valid_bipartite_graph(nx: int, ny: int, edges: typing.List[typing.Tuple[int, int]]) -> bool: ...
def all_unique(x: typing.Iterable[collections.abc.Hashable]) -> bool: ...
