import typing
from typing import Any

class SwitchDirectedGraph:
    def __init__(self, n: int, edges: typing.Iterable[typing.Tuple[int, int]]) -> None: ...
    @property
    def n(self): ...
    @property
    def edges(self) -> typing.Iterator[typing.Tuple[int, int]]: ...
    @property
    def degree_sequence(self) -> typing.Iterable[typing.Tuple[int, int]]: ...
    @staticmethod
    def from_degree_sequence(degree_sequence: typing.Sequence[typing.Tuple[int, int]]) -> SwitchDirectedGraph: ...
    def __eq__(self, other: Any) -> Any: ...
    def switch(self) -> bool: ...
