import typing
from typing import Any

class SwitchSimpleGraph:
    def __init__(self, n: int, edges: typing.Iterable[typing.Set[int]]) -> None: ...
    @property
    def n(self): ...
    @property
    def edges(self) -> typing.Iterator[typing.Set[int]]: ...
    @property
    def degree_sequence(self) -> typing.Tuple[int]: ...
    @staticmethod
    def from_degree_sequence(degree_sequence: typing.Sequence[int]) -> SwitchSimpleGraph: ...
    def __eq__(self, other: Any) -> Any: ...
    def switch(self) -> bool: ...
