import collections
import typing

def valid_bipartite_graph(nx: int, ny: int, edges: typing.List[typing.Tuple[int, int]]) -> bool: ...
def all_unique(x: typing.Iterable[collections.abc.Hashable]) -> bool: ...
def degree_sequence_graphical(dx: typing.Sequence[int], dy: typing.Sequence[int]) -> bool: ...
